### ISSUE TITLE
Add usage example with luasocket or luv (libuv)?

### ISSUE THREAD

**Issue by nikneym** [neoxic/lua-mbedtls#1]
Hi, I like how lightweight mbedtls is and want to use it in my projects but unfortunately bindings seem to be missing some examples. Would be great to see the usage of it with either luasocket or luv.

**Comment by neoxic** [comment]
Using **lua-mbedtls** with any I/O transport (both blocking and non-blocking) is pretty easy, but depends on the underlying I/O API.

In case of LuaSocket, a simple example might look like this:
```Lua
local socket = require 'socket'
local ssl = require 'mbedtls.ssl'

local function read(h, n)
    return assert(h:receive(n))
end

local function write(h, d)
    return assert(h:send(d))
end

local tcp = assert(socket.connect('github.com', 443))
local cfg = ssl.newconfig('tls-client')
local ctx = ssl.newcontext(cfg, read, write, tcp)

ctx:write('GET / HTTP/1.0\r\n\r\n')
print(ctx:read(1000))

ctx:reset()
tcp:close()
```
Output:
```
HTTP/1.1 301 Moved Permanently
Content-Length: 0
Location: https://github.com/
connection: close
```
Please note that the above code is primitive for simplicity, but I hope you'll get the idea.

As for **luv**, making a similar example is not that easy due to the nature of libuv's data reception strategy - it receives as much as currently available whereas Mbed TLS works with chunks of size N (more like the usual `recv(2)`). But with certain skills, one can implement a simple receive queue in order to wrap around Mbed TLS API. I've done that in my Lua projects that use libuv under the hood.

**Comment by neoxic** [comment]
I added this example code to the README: https://github.com/neoxic/lua-mbedtls#usage-example-ssltls-over-luasocket
